update=mié 09 oct 2013 18:35:43 ART
last_client=pcbnew
[pcbnew]
version=1
LastNetListRead=pot.net
UseCmpFile=1
PadDrill="    1,143000"
PadDrillOvalY="    1,143000"
PadSizeH="    1,778000"
PadSizeV="    1,778000"
PcbTextSizeV="    1,500000"
PcbTextSizeH="    1,500000"
PcbTextThickness="    0,300000"
ModuleTextSizeV="    1,500000"
ModuleTextSizeH="    1,500000"
ModuleTextSizeThickness="    0,150000"
SolderMaskClearance="    0,200000"
SolderMaskMinWidth="    0,000000"
DrawSegmentWidth="    0,200000"
BoardOutlineThickness="    0,150000"
ModuleOutlineThickness="    0,150000"
[pcbnew/libraries]
LibDir=
LibName1=sockets
LibName2=connect
LibName3=pin_array
LibName4=divers
LibName5=smd_capacitors
LibName6=smd_resistors
LibName7=smd_crystal&oscillator
LibName8=smd_transistors
LibName9=libcms
LibName10=display
LibName11=led
LibName12=dip_sockets
LibName13=pga_sockets
LibName14=valves
LibName15=logochico
LibName16=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/Comp
LibName17=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/con-phoenix-250
LibName18=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/con-phoenix-381_l
LibName19=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/con-phoenix-500-mstba6
LibName20=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/Epcos-MKT
LibName21=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/Gajda_power
LibName22=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/logo
LibName23=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/logochico
LibName24=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/logogrande
LibName25=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/modificados
LibName26=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/palito
LibName27=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/phoenix_gicv-gf
LibName28=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/phoenixmod
LibName29=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/placa
LibName30=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/potenciometro
LibName31=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/powerint
LibName32=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/relay
LibName33=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/relay_finder
LibName34=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/TO
LibName35=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/TRAFO
LibName36=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/TRAFO (Amid Ale's conflicted copy 2013-07-04)
LibName37=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/varistor
LibName38=/home/turco/Dropbox/variador-dos-partes (segunda edicion)/ZOLODA
LibName39=discret
LibName40=capacitors
